MVC Latest/MVC Latest/Controllers/TransferController.cs
using MVC_Latest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Latest.Controllers
{
    public class TransferController : Controller
    {
        // GET: Transfer
        [Authorize(Roles ="Customer")]
        public ActionResult CheckingtoSaving()
        {
            Transfer chkToSav = new Transfer();
            string username = HttpContext.User.Identity.Name;
            IBusinessAccount iba = GenericFactory<BusinessLayer, IBusinessAccount>.CreateInstance();
            string chkAcctNum = iba.GetCheckingAccountNumber(username);
            chkToSav.chkBalance = iba.GetCheckingBalance(chkAcctNum);
            chkToSav.savBalance = iba.GetSavingBalance(chkAcctNum + "1");
            chkToSav.amtToTransfer = 0;
            chkToSav.status = "";
            return View(chkToSav);
        }

        [Authorize(Roles = "Customer")]
        [HttpPost]
        public ActionResult CheckingtoSaving(Transfer chkToSav)
        {
            string username = HttpContext.User.Identity.Name;
            IBusinessAccount iba = GenericFactory<BusinessLayer, IBusinessAccount>.CreateInstance();
            string chkAcctNum = iba.GetCheckingAccountNumber(username);

            bool res = iba.TransferFromChkgToSavViaSP(chkAcctNum, chkAcctNum + "1", chkToSav.amtToTransfer);
            if (res == true)
            {
                chkToSav.chkBalance = iba.GetCheckingBalance(chkAcctNum);
                chkToSav.savBalance = iba.GetSavingBalance(chkAcctNum + "1");
                chkToSav.status = "Amount transferred Successfully!";
            }
            else
            {
                chkToSav.status = "Amount transfer is not successful..";
            }
            return View(chkToSav);
        }


        //Transfer Logic for Saving to Checking

        [Authorize(Roles = "Customer")]
        public ActionResult SavingtoChecking()
        {
            Transfer chkToSav = new Transfer();
            string username = HttpContext.User.Identity.Name;
            IBusinessAccount iba = GenericFactory<BusinessLayer, IBusinessAccount>.CreateInstance();
            string chkAcctNum = iba.GetCheckingAccountNumber(username);
            chkToSav.chkBalance = iba.GetCheckingBalance(chkAcctNum);
            chkToSav.savBalance = iba.GetSavingBalance(chkAcctNum + "1");
            chkToSav.amtToTransfer = 0;
            chkToSav.status = "";
            return View(chkToSav);
        }

        [Authorize(Roles = "Customer")]
        [HttpPost]
        public ActionResult SavingtoChecking(Transfer savToChk)
        {
            string username = HttpContext.User.Identity.Name;
            IBusinessAccount iba = GenericFactory<BusinessLayer, IBusinessAccount>.CreateInstance();
            string chkAcctNum = iba.GetCheckingAccountNumber(username);

            bool res = iba.TransferSavToChk(chkAcctNum + "1" , chkAcctNum, savToChk.amtToTransfer);
            if (res == true)
            {
                savToChk.chkBalance = iba.GetCheckingBalance(chkAcctNum);
                savToChk.savBalance = iba.GetSavingBalance(chkAcctNum + "1");
                savToChk.status = "Amount transferred Successfully!";
            }
            else
            {
                savToChk.status = "Amount transfer is not successful..";
            }
            return View(savToChk);
        }
    }
}

MVC Latest/MVC Latest/Views/Master.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Styles/style.css" rel="stylesheet" type="text/css" />
    <link href="~/Styles/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    
               
    <div class="header-project">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="/authentication/index">Login</a></li>
            <li><a href="/userinfo/register">Sign Up</a></li>
            <li><a href="/home/index">Home</a></li>
            <li><a href="/home/news">News</a></li>
            <li>@Html.ActionLink("Checking to Saving", "CheckingtoSaving", "Transfer")</li>
            <li><a href="/transfer/SavingtoChecking">Transfer Sav to Chk</a></li>
            <li><a href="/transferhistoy/transferhistoryretrieve">Transfer History</a></li>
            <li><a href="/userinfo/updatepassword">Update Password</a></li>
        </ul>
    </div>
    </br>
    </br>
    <div class="header-bank">
        <!-- Brand and toggle get grouped for better mobile display -->

    </div>







        <div class="col-lg-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>